# Generated by Django 3.2.5 on 2023-01-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20230126_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipkart_data',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
