# Generated by Django 3.2.5 on 2023-01-26 11:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_flipkart_data_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipkart_data',
            name='details',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
