# Generated by Django 3.2.5 on 2023-02-01 10:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_flipkart_data_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazon_data',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='flipkart_data',
            name='discount',
        ),
        migrations.AlterField(
            model_name='flipkart_data',
            name='details',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
