# Generated by Django 3.2.5 on 2023-02-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_amazon_data_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('product_type', models.CharField(max_length=255)),
            ],
        ),
    ]
