# Generated by Django 3.2.5 on 2023-02-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_scrap_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap_links',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
